database:
  type: mysql  # mysql, postgres, or sqlite
  host: localhost
  port: 3306
  user: lychee
  password: your_password
  database: lychee
  # For SQLite, use path instead:
  # path: /path/to/lychee.db

server:
  port: 8080
  cors:
    allowed_origins:
      - http://localhost:5173  # Vite dev server
      - http://localhost:3000  # Alternative dev port

# Base URL of your Lychee installation (used to construct photo URLs)
lychee_base_url: https://your-lychee-domain.com

# Ollama AI integration for photo title suggestions (optional)
ollama:
  url: http://localhost:11434  # Ollama server URL
  model: qwen2.5vl:3b          # Model name (e.g., qwen2.5vl:3b, llava:7b)

# OpenAI-style API integration for photo title suggestions (optional)
openai:
  url: https://api.openai.com/v1/chat/completions  # API endpoint URL
  api_key: your-api-key-here                       # API key for authentication
  model: gpt-4o                                    # Model name (optional, defaults to gpt-4o)
